### PR TITLE
Fix "Mesh not found: techpack_stairway_slope.obj" error on start

### PR DESCRIPTION
**Pull request by andrenete**
Fix `Mesh not found: techpack_stairway_slope.obj` error on start by adding missing obj file taken from https://github.com/joe7575/techpack_stairway.

Fixes https://github.com/BlockySurvival/issue-tracker/issues/274

### CODE REVIEW

**Comment by joe7575** [comment]
I don't recommend to use the stairs and slopes from the  `moreblocks` mod. At most additionally, because the slope object from [here](https://github.com/joe7575/techpack_stairway) is minimally smaller in order to avoid graphic disturbances and has a special function "after_place_node" to optimize the placement alignment.
The question is whether TechPack Stairway shouldn't be removed from the Mod Pack in favor of the standalone version.

**Comment by andrenete** [comment]
Your points about z-fighting and placement alignment are valid, but the best solution is to fix this directly in `moreblocks` to avoid creating incompatible implementations and to not duplicate code, which in turn will improve the player experience.

For this PR, should I remove the `moreblocks` part and replace the `moreblocks` mesh with one from the attached link? If you think that removing `techpack_stairway` from the modpack is the way to go, feel free to close this PR without merging.

**Comment by andrenete** [comment]
Another thought: before removing a `techpack_stairway` from modpack completely, you should probably wait and first notify its users about the switch to standalone version, for example by writing a warning in `minetest.log` and in modpack `README.md`.

**Comment by andrenete** [comment]
Since you are considering removing `techpack_stairway` from the modpack, I think it would be better not to introduce new features here.

I removed the `moreblocks` part. It is just a bugfix now.

**Comment by joe7575** [comment]
You are right, I should not remove it from the modpack. With this PR it should work as expected. There are no plans from my side to change the mod in the near future, so I keep it as is. Thanks a lot.

**Pull request merged**
