### PR TITLE
Add drops for active tubelib machines and fix end wrench crash bug

### LINKED ISSUE #65: Add drops for active tubelib machines and fix end wrench crash bug
Pull request to fix a couple of crash-causing bugs:

- Add drops for active tubelib machines to ensure that players can't obtain them with, i. e., a node replacer
- Punching a mesecons converter with an end wrench causes a crash because its on_receive_message function returns the wrong thing; fixed that

#64

### PR DESCRIPTION
**Pull request by afkplayer5000**
- Add drops for active tubelib machines to ensure that players can't obtain them with, i. e., a node replacer
- Punching a mesecons converter with an end wrench causes a crash because its on_receive_message function returns the wrong thing; fixed that

Messy pull request b/c I'm a github noob

Closes #65 
Closes BlockySurvival/issue-tracker#270

### CODE REVIEW

**Comment by joe7575** [comment]
> Add drops for active tubelib machines to ensure that players can't obtain them with, i. e., a node replacer

- What do they get instead of?
- What is the sense and purpose of a node replacer?
- Did you consider [NodeStates:on_dig_node](https://github.com/joe7575/techpack/blob/master/tubelib/node_states.lua#L444)?

**Comment by afkplayer5000** [comment]
- An ordinary, non-active tubelib
- It's a mod that aids players in replacing nodes with different nodes; it uses the ordinary on_dig callback but isn't 100% well-behaved
- I did not. That seems to be a better way to accomplish this, will look at.

**Comment by afkplayer5000** [comment]
I tested a fix in NodeStates:on_dig_node:

```
	if meta:get_int("tubelib_state") == RUNNING then
		self:stop(pos, meta)
		node = minetest.get_node(pos)
	end
```

However, as far as I can tell, the can_dig and on_dig callbacks that call the aforementioned function are only defined for the passive node and not the active one on each tubelib. This makes sense, as the active tubelib was never meant to be diggable. I see two options here:

- Add can_dig and on_dig callbacks to the active form of each tubelib machine, and add the above code into NodeStates:on_dig_node
- Add a dummy can_dig callback to each active node that always returns false (this solution seems better to me)

**Comment by joe7575** [comment]
Alternatively the replacer tool supports a blacklist. But this is no general solution, only a mod related. Better would be to add the unofficial but common used group `unbreakable` to all active nodes. But unfortunately, this is so far not supported by the replacer. 
If I have to decide between your two proposals, I recoment the second one, but I prefer the `unbreakable` approach.

**Comment by afkplayer5000** [comment]
This [forum post](https://forum.minetest.net/viewtopic.php?p=172046&sid=313844a79f6ac3eb73a03b536ddf6308#p172046) highlights a number of different ways blocks can get broken when they shouldn't; I'll put together a pull request for the can_dig approach. Even if it's not the ideal solution, it fixes the immediate problem, is mod independent, and is a step in the right direction.

**Comment by afkplayer5000** [comment]
Split into new pull requests #70 for the digging fix and #71 for the end wrench crash

**Pull request closed without merging**
