### PR TITLE
Add a prototype dispenser, capable of placing, using, and shooting items

### PR DESCRIPTION
**Pull request by oversword**
This is a prototype, it should be tested and refined before merging

Abilities:
- Can place nodes, or calls the `on_place` callback
- Can use items, calling the `on_use` calback
- Can shoot items out
- Interact with mobs, feed, milk, capture and place them

TODO:
- ~~Needs a craft - just testing in creative for the moment, craft copied from the high-perf distributor but disabled~~
  Added a basic craft, let me know if you want it changed
- ~~Needs more thoughtful textures, currently it looks like a normal box with the active face highlighted with the high-perf border, we could do with at least one custom texture to distinguish it, and perhaps more thought put into what the non-distinct faces should be too. Once this is done we should review the dependencies as it only depends on `tubelib_addons3` and `tubelib` for the textures (technically this could work without tubelib, like the gravelsieve, you just put the items in manually)~~
  I have added textures, ~~I decided to use the funnel texture & nodebox design for the active face~~ using a nodebox makes the "spit" out item get stuck in the block, had to go with a full block design, I have added an icon for the sides of the dispenser which is supposed to represent a player hand
- ~~Default registration? Perhaps it would be preferable to register all items by default - for my personal applications I'd rather enable them one-by-one to make sure it's not OP, but I can imagine some (if not most) people just wanting everything to work~~
  This should now be easy through the default action, it is now complex enough that you can provide one config for all items if desired
- Defensive code - this can cause a crash when some items are used, mainly because the player is not a userdata object but a table proxying one, we should probably just wrap the action code in a pcall
- ~~Find out if it is at all possible to create a proper fake player instead of using a table~~
  Issue discussed here https://github.com/minetest/minetest/issues/11477 , looks like I can interact with entities just fine with the current work-around
- ~~Allow pointing the dispenser up & down? This is not currently enabled because tubelib doesn't do that by default, but it should be possible~~
  Copied from mesecons piston, active face changed to front, I will need to do some work to make this work with tubelib
- ~~Allow the dispenser to be movable? This might make it OP~~
  Already movable, this is a server config thing
- ~~Allow for different overflow behaviours - perhaps spitting out the item is not ideal, perhaps it should become blocked~~
  Done

### CODE REVIEW

**Comment by oversword** [comment]
@joe7575 this is about ready for you to take a look if you want to let me know what you think about this feature

**Comment by joe7575** [comment]
Give me some time, I'm currently working hard on the Techage mod (bug fixing after a major restructuring).

Have you ever thought about creating something like your own extension mod for TechPack?

**Comment by oversword** [comment]
Don't tempt me! I make these changes in techpack because I think everyone should be able to have them. I don't mind it taking a while, and I may add this as a custom item on our server if it doesn't go through before I plan to do the next update.
If you feel this isn't an appropriate item for techpack then feel free to reject it, I'm just putting it out there and letting you know :)

**Comment by joe7575** [comment]
I still haven't understood what it's supposed to be good for. Do you have some use cases?
Is it intended that one can endless generate items, e.g. diamond blocks?

**Comment by fluxionary** [comment]
> I still haven't understood what it's supposed to be good for. Do you have some use cases?
> Is it intended that one can endless generate items, e.g. diamond blocks?

for use cases, see

https://gitlab.com/VanessaE/pipeworks/-/wikis/home#deployers
https://gitlab.com/VanessaE/pipeworks/-/wikis/home#node-breakers

and all the things that players do with those.

**Comment by oversword** [comment]
> I still haven't understood what it's supposed to be good for. Do you have some use cases?

- Automating mobs: can feed them by right clicking them with food, can pick them up by right clicking them with a lasso / net, can place them in the world, can milk cows with a bucket or shear sheep
- Automating seed farming: Mithril scythe can be used, and the seeds picked up, you can also hoe dirt, plant seeds, and then harvest them by  breaking them (I think), but returning the seeds - something which can't be achieved with the techpack harvester
- Can not only pick up water / lava / river water, but place it down too
- Can place any node down, which makes the automation of things like mossy cobble possible, or the automatic construction of entire machines / builds
- Can automatically repair tubelib machines by using the repair kit (I thought about the balance of this, the dispenser wears out much quicker than other machines, to make this useful you would have to detect the machine defecting and only power the dispenser on when you see a defect, then also turn the repaired machine back on, making this a complex multi-node solution if you want it to be useful - possible with digilines)
- Can automatically rotate nodes by using the screwdriver on them

> Is it intended that one can endless generate items, e.g. diamond blocks?
No, if you're seeing this you're probably in creative mode, this is a bit of a downside, mainly for testing machines in creative mode, but it's hard to avoid with the way I'm making a fake player


I do not believe this will / can operate as a node breaker, think the quarry fills that role well enough for most things, it only operates on things instantaneously and cannot "hold" an action like mining a node for a duration of time.

**Comment by joe7575** [comment]
> P.S. I have a few random questions unrelated to this PR, what would be the best place to discuss them?

I propose by email

**Comment by joe7575** [comment]
I've thought about it.
This is too big a change to the mod for me. 
I will be responsible for this in the future and may have to update/maintain the code.
I prefer you make your own mod and your name out of it. I have no intention of changing tubelib so there shouldn't be any compatibility issues in the future.

**Pull request closed without merging**
